site_name: R-Type Networked
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.code.select
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
